server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type_aliasese-package: com.example.entity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url:
